### ISSUE TITLE
No Menu?

### ISSUE THREAD

**Issue by mke21** [Sommerregen/grav-theme-aerial#1]
Hi,

I am a new user of grav, so sorry for the noob question. 
There does not seem to be any navigation part in this theme. I've created a couple of test pages, but no menu to be seen. How do can I navigate to those pages with this theme?

**Comment by Sommerregen** [comment]
Hi @mke21,

yes **Aerial** is a one page theme meaning it presents everything on the same page and therefore a navigation menu doesn't exist. You have to write it on your own or copy it e.g. from [Antimatter](https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/navigation.html.twig).
