### ISSUE TITLE
Demo of this theme does not work

### ISSUE THREAD

**Issue by awrog** [Sommerregen/grav-theme-aerial#2]
When I click on Demo of this theme (http://themes.benjamin-regler.de/aerial/) I get an error in the following lines:

![2016-12-21 08_55_59-crikey there was an error](https://cloud.githubusercontent.com/assets/12153667/21381406/686cf3c2-c75b-11e6-99ab-789235022068.png)

**Comment by Sommerregen** [comment]
Hi @awrog ,

thanks I didn't noticed that. It is fixed now and was due to a change I did (changed the cache provider).
